apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: {{ required "Customer name is required" .Values.customerName }}-default-deny
  namespace: {{ required "Customer Name is required" .Values.customerName }}-ns
spec:
  podSelector: {}
  policyTypes: 
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}