apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "Customer Name is required" .Values.customerName }}-sa
  namespace:  {{ required "Customer Name is required" .Values.customerName }}-ns
