# ALL CUSTOMER SPECIFC VALUES MUST BE INCLUDED HERE. 

customerName: customer-1

limitRange:
  default:
    cpu: "500m"
    memory: "1Gi"
  defaultRequest:
    cpu: "250m"
    memory: "512Mi"

resourceQuota:
  cpu: "2"
  memory: "4Gi"

entraIDGroup: "customer-1-group"


